"""
WatchTower SIEM - Built-in Detection Rules
50+ rules covering MITRE ATT&CK techniques mapped to Windows Event IDs.
"""

BUILTIN_RULES = [

    # ══════════════════════════════════════════════════════════════════════════
    # AUTHENTICATION & CREDENTIAL ACCESS
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Brute Force - Multiple Failed Logons",
        "description": "Detects 10+ failed logon attempts from the same host in 5 minutes.",
        "category": "authentication",
        "severity": "high",
        "mitre_technique": ["T1110.001"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4625], "threshold": 10, "window_seconds": 300, "exclude_machine_accounts": True},
        "references": ["https://attack.mitre.org/techniques/T1110/001/"],
        "tags": ["brute_force", "authentication"],
        "sigma_rule_id": "win_security_susp_failed_logons_explicit_credentials",
    },
    {
        "name": "Account Lockout",
        "description": "User account locked out — possible brute force or credential stuffing.",
        "category": "authentication",
        "severity": "high",
        "mitre_technique": ["T1110"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4740]},
        "tags": ["lockout", "authentication"],
    },
    {
        "name": "Successful Logon After Multiple Failures",
        "description": "Successful logon (4624) on a host with 5+ prior failures — may indicate successful brute force.",
        "category": "authentication",
        "severity": "critical",
        "mitre_technique": ["T1110"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4624], "threshold": 1, "window_seconds": 300},
        "tags": ["brute_force_success", "authentication"],
    },
    {
        "name": "Kerberos Pre-Authentication Failure",
        "description": "Kerberos pre-auth failure (4771) — may indicate password spray against AD accounts.",
        "category": "authentication",
        "severity": "medium",
        "mitre_technique": ["T1110.003"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4771]},
        "tags": ["kerberos", "password_spray"],
    },
    {
        "name": "Password Spray - Multiple Accounts Same Source",
        "description": "5+ account logon failures from same host in 2 minutes — indicative of password spraying.",
        "category": "authentication",
        "severity": "critical",
        "mitre_technique": ["T1110.003"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4625], "threshold": 5, "window_seconds": 120, "exclude_machine_accounts": True},
        "tags": ["password_spray", "authentication"],
    },
    {
        "name": "Logon with Explicit Credentials (runas)",
        "description": "User logged on using explicit credentials (4648) — may indicate lateral movement or runas abuse.",
        "category": "authentication",
        "severity": "medium",
        "mitre_technique": ["T1550.002"],
        "mitre_tactic": ["Lateral Movement"],
        "condition": {"event_ids": [4648], "exclude_machine_accounts": True},
        "tags": ["explicit_credentials", "runas"],
    },
    {
        "name": "Special Logon (Admin Equivalent Privileges)",
        "description": "Special logon granting admin-equivalent privileges created (4672). Monitor for unexpected use.",
        "category": "authentication",
        "severity": "medium",
        "mitre_technique": ["T1078"],
        "mitre_tactic": ["Privilege Escalation"],
        "condition": {"event_ids": [4672]},
        "tags": ["special_logon", "privilege"],
    },
    {
        "name": "RDP Remote Logon Detected",
        "description": "Remote Desktop (Type 10) logon detected — monitor for unexpected RDP connections.",
        "category": "authentication",
        "severity": "medium",
        "mitre_technique": ["T1021.001"],
        "mitre_tactic": ["Lateral Movement"],
        "condition": {"event_ids": [4624], "fields": {"logon_type": "10"}, "exclude_machine_accounts": True},
        "tags": ["rdp", "remote_access", "lateral_movement"],
    },
    {
        "name": "NTLM Network Logon (Pass-the-Hash Indicator)",
        "description": "Network logon (Type 3) with NTLM — potential Pass-the-Hash attack.",
        "category": "credential_access",
        "severity": "high",
        "mitre_technique": ["T1550.002"],
        "mitre_tactic": ["Lateral Movement"],
        "condition": {"event_ids": [4624], "fields": {"logon_type": "3"}},
        "tags": ["pass_the_hash", "ntlm", "lateral_movement"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PRIVILEGE ESCALATION & ACCOUNT MANAGEMENT
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "User Added to Privileged Group",
        "description": "A user was added to a sensitive group (Administrators, Domain Admins) — Events 4728/4732/4756.",
        "category": "account_management",
        "severity": "critical",
        "mitre_technique": ["T1098"],
        "mitre_tactic": ["Privilege Escalation", "Persistence"],
        "condition": {"event_ids": [4728, 4732, 4756]},
        "tags": ["privilege_escalation", "group_membership"],
        "references": ["https://attack.mitre.org/techniques/T1098/"],
    },
    {
        "name": "New User Account Created",
        "description": "A new local user account was created (4720) — verify this is authorized.",
        "category": "account_management",
        "severity": "high",
        "mitre_technique": ["T1136.001"],
        "mitre_tactic": ["Persistence"],
        "condition": {"event_ids": [4720]},
        "tags": ["account_creation", "persistence"],
    },
    {
        "name": "Token Privilege Enabled",
        "description": "A sensitive privilege was enabled for a process (4703) — used in privilege escalation chains.",
        "category": "privilege_escalation",
        "severity": "medium",
        "mitre_technique": ["T1134.001"],
        "mitre_tactic": ["Privilege Escalation"],
        "condition": {"event_ids": [4703]},
        "tags": ["privilege_enabled", "token"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PROCESS EXECUTION & LIVING OFF THE LAND
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Mimikatz Credential Dumping",
        "description": "Mimikatz or lsass credential dumping tool detected by process name.",
        "category": "credential_access",
        "severity": "critical",
        "mitre_technique": ["T1003.001"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "mimikatz"}}},
        "tags": ["mimikatz", "credential_dump"],
        "references": ["https://attack.mitre.org/techniques/T1003/001/"],
    },
    {
        "name": "Suspicious PowerShell Encoded Command",
        "description": "PowerShell launched with -EncodedCommand flag — common for obfuscated malicious scripts.",
        "category": "powershell",
        "severity": "high",
        "mitre_technique": ["T1059.001"],
        "mitre_tactic": ["Execution"],
        "condition": {"event_ids": [4688, 1, 4103, 4104], "fields": {"command_line": {"contains": "-enc"}}},
        "tags": ["powershell", "encoded_command", "obfuscation"],
        "references": ["https://attack.mitre.org/techniques/T1059/001/"],
    },
    {
        "name": "PowerShell Download Cradle",
        "description": "PowerShell used to download content from the internet (DownloadString/IEX).",
        "category": "powershell",
        "severity": "critical",
        "mitre_technique": ["T1059.001", "T1105"],
        "mitre_tactic": ["Execution", "Command and Control"],
        "condition": {"event_ids": [4103, 4104, 4688], "fields": {"command_line": {"contains": "downloadstring"}}},
        "tags": ["powershell", "download_cradle", "c2"],
    },
    {
        "name": "PowerShell ExecutionPolicy Bypass",
        "description": "PowerShell launched with -ExecutionPolicy Bypass — used to run unsigned scripts.",
        "category": "powershell",
        "severity": "high",
        "mitre_technique": ["T1059.001"],
        "mitre_tactic": ["Execution"],
        "condition": {"event_ids": [4688, 4103, 4104], "fields": {"command_line": {"contains": "bypass"}}},
        "tags": ["powershell", "bypass", "execution_policy"],
    },
    {
        "name": "WMI Remote Execution",
        "description": "WMI process spawning or remote execution — common lateral movement technique.",
        "category": "wmi",
        "severity": "high",
        "mitre_technique": ["T1047"],
        "mitre_tactic": ["Lateral Movement", "Execution"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "wmic"}}},
        "tags": ["wmi", "lateral_movement"],
        "references": ["https://attack.mitre.org/techniques/T1047/"],
    },
    {
        "name": "Certutil Abuse (File Download/Decode)",
        "description": "certutil.exe used to decode or download files — common malware dropper technique.",
        "category": "defense_evasion",
        "severity": "high",
        "mitre_technique": ["T1140"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "certutil"}}},
        "tags": ["certutil", "lolbin", "defense_evasion"],
    },
    {
        "name": "Mshta Script Execution",
        "description": "mshta.exe used to execute scripts — common phishing payload delivery.",
        "category": "defense_evasion",
        "severity": "high",
        "mitre_technique": ["T1218.005"],
        "mitre_tactic": ["Defense Evasion", "Execution"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "mshta"}}},
        "tags": ["mshta", "lolbin", "phishing"],
    },
    {
        "name": "Regsvr32 Script Execution (Squiblydoo)",
        "description": "regsvr32.exe used to execute COM scriptlets — Squiblydoo bypass technique.",
        "category": "defense_evasion",
        "severity": "high",
        "mitre_technique": ["T1218.010"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [4688, 1], "fields": {"command_line": {"contains": "regsvr32"}}},
        "tags": ["regsvr32", "squiblydoo", "lolbin"],
    },
    {
        "name": "Rundll32 Suspicious Execution",
        "description": "rundll32.exe executing with suspicious parameters — LOLBin abuse.",
        "category": "defense_evasion",
        "severity": "medium",
        "mitre_technique": ["T1218.011"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "rundll32"}}},
        "tags": ["rundll32", "lolbin"],
    },
    {
        "name": "Net User / Group Enumeration",
        "description": "net.exe used to enumerate users or groups — common post-exploitation reconnaissance.",
        "category": "lateral_movement",
        "severity": "medium",
        "mitre_technique": ["T1087.001"],
        "mitre_tactic": ["Discovery"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "net.exe"}}},
        "tags": ["net_user", "enumeration", "discovery"],
    },
    {
        "name": "Whoami Post-Exploitation",
        "description": "whoami.exe executed — frequently used post-exploitation to determine user context.",
        "category": "process_execution",
        "severity": "low",
        "mitre_technique": ["T1033"],
        "mitre_tactic": ["Discovery"],
        "condition": {"event_ids": [4688, 1], "fields": {"process_name": {"contains": "whoami"}}},
        "tags": ["whoami", "discovery", "post_exploitation"],
    },
    {
        "name": "Office Application Spawning Shell",
        "description": "Microsoft Office (Word/Excel/Outlook) spawned cmd or PowerShell — macro/phishing execution.",
        "category": "process_execution",
        "severity": "critical",
        "mitre_technique": ["T1566.001"],
        "mitre_tactic": ["Initial Access", "Execution"],
        "condition": {"event_ids": [4688, 1], "fields": {"parent_process": {"contains": "winword"}}},
        "tags": ["office_macro", "phishing", "initial_access"],
        "references": ["https://attack.mitre.org/techniques/T1566/001/"],
    },
    {
        "name": "Excel Spawning Suspicious Process",
        "description": "Excel.exe spawned a child process — possible macro execution or spreadsheet-based phishing.",
        "category": "process_execution",
        "severity": "critical",
        "mitre_technique": ["T1566.001"],
        "mitre_tactic": ["Initial Access", "Execution"],
        "condition": {"event_ids": [4688, 1], "fields": {"parent_process": {"contains": "excel"}}},
        "tags": ["excel_macro", "phishing"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # PERSISTENCE
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "New Scheduled Task Created",
        "description": "A new scheduled task was created (4698) — commonly used for persistence.",
        "category": "scheduled_task",
        "severity": "medium",
        "mitre_technique": ["T1053.005"],
        "mitre_tactic": ["Persistence", "Privilege Escalation"],
        "condition": {"event_ids": [4698]},
        "tags": ["scheduled_task", "persistence"],
        "references": ["https://attack.mitre.org/techniques/T1053/005/"],
    },
    {
        "name": "Scheduled Task Modified",
        "description": "Existing scheduled task modified (4702) — may indicate persistence hijacking.",
        "category": "scheduled_task",
        "severity": "high",
        "mitre_technique": ["T1053.005"],
        "mitre_tactic": ["Persistence"],
        "condition": {"event_ids": [4702]},
        "tags": ["scheduled_task", "persistence", "modification"],
    },
    {
        "name": "New Windows Service Installed",
        "description": "A new Windows service was installed (7045) — common persistence/privilege escalation method.",
        "category": "service",
        "severity": "high",
        "mitre_technique": ["T1543.003"],
        "mitre_tactic": ["Persistence", "Privilege Escalation"],
        "condition": {"event_ids": [7045]},
        "tags": ["service", "persistence"],
        "references": ["https://attack.mitre.org/techniques/T1543/003/"],
    },
    {
        "name": "Service Configuration Changed",
        "description": "Windows service reconfigured (7040) — may indicate service hijacking.",
        "category": "service",
        "severity": "medium",
        "mitre_technique": ["T1543.003"],
        "mitre_tactic": ["Persistence"],
        "condition": {"event_ids": [7040]},
        "tags": ["service", "persistence", "modification"],
    },
    {
        "name": "Registry Run Key Modified",
        "description": "Registry autorun key modified — classic persistence via HKLM/HKCU Run keys.",
        "category": "registry",
        "severity": "high",
        "mitre_technique": ["T1547.001"],
        "mitre_tactic": ["Persistence", "Privilege Escalation"],
        "condition": {"event_ids": [4657, 13], "fields": {"registry_key": {"contains": "\\run"}}},
        "tags": ["registry", "autorun", "persistence"],
        "references": ["https://attack.mitre.org/techniques/T1547/001/"],
    },
    {
        "name": "Startup Folder File Modification",
        "description": "File created/modified in a Windows Startup folder — persistence technique.",
        "category": "persistence",
        "severity": "high",
        "mitre_technique": ["T1547.001"],
        "mitre_tactic": ["Persistence"],
        "condition": {"event_ids": [4663, 11], "fields": {"file_path": {"contains": "startup"}}},
        "tags": ["startup_folder", "persistence"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # LATERAL MOVEMENT
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "PsExec Remote Execution",
        "description": "PsExec/PSEXESVC service created — common tool for lateral movement.",
        "category": "lateral_movement",
        "severity": "critical",
        "mitre_technique": ["T1569.002"],
        "mitre_tactic": ["Lateral Movement", "Execution"],
        "condition": {"event_ids": [7045, 4688], "fields": {"service_name": {"contains": "psexec"}}},
        "tags": ["psexec", "lateral_movement"],
        "references": ["https://attack.mitre.org/techniques/T1569/002/"],
    },
    {
        "name": "Admin Share Access (SMB Lateral Movement)",
        "description": "Access to administrative shares (ADMIN$, C$, IPC$) — indicator of lateral movement.",
        "category": "lateral_movement",
        "severity": "high",
        "mitre_technique": ["T1021.002"],
        "mitre_tactic": ["Lateral Movement"],
        "condition": {"event_ids": [5140]},
        "tags": ["smb", "admin_share", "lateral_movement"],
        "references": ["https://attack.mitre.org/techniques/T1021/002/"],
    },
    {
        "name": "Remote Service Creation",
        "description": "Service created on a remote system (4697) — lateral movement via service manager.",
        "category": "lateral_movement",
        "severity": "high",
        "mitre_technique": ["T1543.003"],
        "mitre_tactic": ["Lateral Movement", "Persistence"],
        "condition": {"event_ids": [4697]},
        "tags": ["remote_service", "lateral_movement"],
    },
    {
        "name": "Active Directory Enumeration (BloodHound)",
        "description": "High-volume LDAP queries detected — typical of BloodHound/ldapdomaindump domain enumeration.",
        "category": "lateral_movement",
        "severity": "high",
        "mitre_technique": ["T1018", "T1069.002"],
        "mitre_tactic": ["Discovery"],
        "condition": {"event_ids": [4662], "threshold": 20, "window_seconds": 60},
        "tags": ["ad_enumeration", "bloodhound", "discovery"],
        "references": ["https://attack.mitre.org/techniques/T1018/"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # DEFENSE EVASION
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Windows Defender Disabled",
        "description": "Windows Defender real-time protection disabled — potential defense evasion.",
        "category": "defense_evasion",
        "severity": "critical",
        "mitre_technique": ["T1562.001"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [5001, 5010, 5012]},
        "tags": ["defender", "av_disabled", "defense_evasion"],
        "references": ["https://attack.mitre.org/techniques/T1562/001/"],
    },
    {
        "name": "Audit Policy Changed",
        "description": "System audit policy changed (4719) — attackers disable logging to hide tracks.",
        "category": "defense_evasion",
        "severity": "high",
        "mitre_technique": ["T1562.002"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [4719]},
        "tags": ["audit_policy", "defense_evasion"],
    },
    {
        "name": "Security Event Log Cleared",
        "description": "Windows Security event log was cleared (1102) — critical indicator of cover-up activity.",
        "category": "defense_evasion",
        "severity": "critical",
        "mitre_technique": ["T1070.001"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [1102]},
        "tags": ["log_cleared", "defense_evasion", "cover_tracks"],
        "references": ["https://attack.mitre.org/techniques/T1070/001/"],
    },
    {
        "name": "System Event Log Cleared",
        "description": "Windows System event log was cleared (104) — part of a cover-up attempt.",
        "category": "defense_evasion",
        "severity": "critical",
        "mitre_technique": ["T1070.001"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [104]},
        "tags": ["log_cleared", "defense_evasion"],
    },
    {
        "name": "Windows Firewall Rule Added",
        "description": "New Windows Firewall rule added (4946) — may allow C2 traffic.",
        "category": "defense_evasion",
        "severity": "medium",
        "mitre_technique": ["T1562.004"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [4946]},
        "tags": ["firewall", "defense_evasion"],
    },
    {
        "name": "Group Policy Object Modified",
        "description": "GPO modified (5136) — can distribute malware or weaken security settings across the domain.",
        "category": "defense_evasion",
        "severity": "high",
        "mitre_technique": ["T1484.001"],
        "mitre_tactic": ["Defense Evasion", "Privilege Escalation"],
        "condition": {"event_ids": [5136]},
        "tags": ["gpo", "group_policy", "defense_evasion"],
        "references": ["https://attack.mitre.org/techniques/T1484/001/"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # CREDENTIAL DUMPING & FILE SYSTEM
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "SAM Database Access",
        "description": "SAM database accessed directly (4661) — credential harvesting technique.",
        "category": "credential_access",
        "severity": "critical",
        "mitre_technique": ["T1003.002"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4661]},
        "tags": ["sam", "credential_dump"],
    },
    {
        "name": "NTDS.dit Access (Domain Controller Dump)",
        "description": "Access to NTDS.dit file detected — the AD database containing all password hashes.",
        "category": "credential_access",
        "severity": "critical",
        "mitre_technique": ["T1003.003"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4663], "fields": {"file_path": {"contains": "ntds.dit"}}},
        "tags": ["ntds", "dc_dump", "credential_dump"],
        "references": ["https://attack.mitre.org/techniques/T1003/003/"],
    },
    {
        "name": "DCSync Attack",
        "description": "Directory Replication request from non-DC machine — classic DCSync credential harvesting.",
        "category": "credential_access",
        "severity": "critical",
        "mitre_technique": ["T1003.006"],
        "mitre_tactic": ["Credential Access"],
        "condition": {"event_ids": [4662]},
        "tags": ["dcsync", "credential_dump", "ad_attack"],
        "references": ["https://attack.mitre.org/techniques/T1003/006/"],
    },
    {
        "name": "Suspicious File Created in System32",
        "description": "New file created in System32 or SysWOW64 — common malware drop location.",
        "category": "file_system",
        "severity": "high",
        "mitre_technique": ["T1036.005"],
        "mitre_tactic": ["Defense Evasion"],
        "condition": {"event_ids": [11], "fields": {"file_path": {"contains": "system32"}}},
        "tags": ["file_system", "masquerading"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # RANSOMWARE & IMPACT
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Shadow Copy Deletion",
        "description": "Volume Shadow Copy deletion detected — critical ransomware pre-encryption step.",
        "category": "defense_evasion",
        "severity": "critical",
        "mitre_technique": ["T1490"],
        "mitre_tactic": ["Impact"],
        "condition": {"event_ids": [4688, 1], "fields": {"command_line": {"contains": "shadowcopy"}}},
        "tags": ["shadow_copy", "ransomware", "impact"],
        "references": ["https://attack.mitre.org/techniques/T1490/"],
    },
    {
        "name": "BCDEdit Boot Recovery Disabled",
        "description": "BCDEdit used to disable Windows recovery — ransomware prevents system restoration.",
        "category": "defense_evasion",
        "severity": "critical",
        "mitre_technique": ["T1490"],
        "mitre_tactic": ["Impact"],
        "condition": {"event_ids": [4688, 1], "fields": {"command_line": {"contains": "bcdedit"}}},
        "tags": ["bcdedit", "ransomware", "boot_recovery"],
    },
    {
        "name": "Backup Catalog Deletion (wbadmin)",
        "description": "Windows backup catalog deleted via wbadmin — ransomware pre-encryption step.",
        "category": "defense_evasion",
        "severity": "critical",
        "mitre_technique": ["T1490"],
        "mitre_tactic": ["Impact"],
        "condition": {"event_ids": [4688, 1], "fields": {"command_line": {"contains": "wbadmin"}}},
        "tags": ["backup_deletion", "ransomware", "impact"],
    },
    {
        "name": "Mass File Modification (Potential Ransomware)",
        "description": "100+ file write events in 60 seconds — potential ransomware encryption activity.",
        "category": "file_system",
        "severity": "critical",
        "mitre_technique": ["T1486"],
        "mitre_tactic": ["Impact"],
        "condition": {"event_ids": [4663, 11], "threshold": 100, "window_seconds": 60},
        "tags": ["ransomware", "mass_modification", "impact"],
        "references": ["https://attack.mitre.org/techniques/T1486/"],
    },

    # ══════════════════════════════════════════════════════════════════════════
    # NETWORK & DATA COLLECTION
    # ══════════════════════════════════════════════════════════════════════════
    {
        "name": "Suspicious Outbound Network Connection",
        "description": "Process making outbound network connection — potential C2 beaconing.",
        "category": "network",
        "severity": "medium",
        "mitre_technique": ["T1071.001"],
        "mitre_tactic": ["Command and Control"],
        "condition": {"event_ids": [3]},
        "tags": ["network", "c2", "outbound"],
    },
    {
        "name": "PowerShell Network Activity",
        "description": "PowerShell.exe making direct network connections — possible C2 beaconing.",
        "category": "powershell",
        "severity": "high",
        "mitre_technique": ["T1059.001", "T1071"],
        "mitre_tactic": ["Command and Control", "Execution"],
        "condition": {"event_ids": [3, 5156], "fields": {"process_name": {"contains": "powershell"}}},
        "tags": ["powershell", "network", "c2"],
    },
    {
        "name": "Network Share Created",
        "description": "New network share created (5142) — may indicate data staging for exfiltration.",
        "category": "network",
        "severity": "medium",
        "mitre_technique": ["T1039"],
        "mitre_tactic": ["Collection"],
        "condition": {"event_ids": [5142]},
        "tags": ["network_share", "exfiltration"],
    },
    {
        "name": "USB Storage Device Inserted",
        "description": "Removable storage device connected (6416) — potential data exfiltration via USB.",
        "category": "file_system",
        "severity": "low",
        "mitre_technique": ["T1052.001"],
        "mitre_tactic": ["Exfiltration"],
        "condition": {"event_ids": [6416]},
        "tags": ["usb", "removable_storage", "exfiltration"],
    },
    {
        "name": "Network Port Scanning Detected",
        "description": "High-volume failed network connections from single host — potential port scan.",
        "category": "network",
        "severity": "medium",
        "mitre_technique": ["T1046"],
        "mitre_tactic": ["Discovery"],
        "condition": {"event_ids": [5156, 5157], "threshold": 50, "window_seconds": 60},
        "tags": ["port_scan", "discovery", "network"],
    },
]
